### ISSUE TITLE
Extension Host Terminated Unexpectedly

### ISSUE THREAD

**Issue by tedonmain** [ritwickdey/vscode-live-server#266]
Steps to reproduce in VSCode Insiders Version 1.31.0-insider (1.31.0-insider) on MacOS 10.14.2 : (note: works as expected in VSCode Version 1.30.2 (1.30.2))
In VSCode Extensions search for/install Live Server. 
Message window: Extension host terminated unexpected
Option Buttons: 
1) Open Developer Tools (nice feature!) 
2) Restart Extension Host -- selecting this restarts and error is reported again repeatedly

DevTools Console:
workbench.main.js:sourcemap:3334 [Extension Host] debugger listening on port 27411
workbench.main.js:sourcemap:3332 Extension Host
workbench.main.js:sourcemap:3332 Debugger listening on ws://127.0.0.1:27411/f48f0e98-d855-4469-8af7-13cb5413de47
For help, see: https://nodejs.org/en/docs/inspector

/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3500 Extension host terminated unexpectedly. Code:  null  Signal:  SIGABRT
t._onExtensionHostCrashed @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3500
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2542 Extension host terminated unexpectedly.
t.onDidNotificationChange @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2542
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3332 Extension Host
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3332 dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/gonzo/.vscode-insiders/extensions/ritwickdey.liveserver-5.3.1/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/gonzo/.vscode-insiders/extensions/ritwickdey.liveserver-5.3.1/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1523  INFO no standard startup: not just one text editor
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3334 [Extension Host] debugger listening on port 44626
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3332 Extension Host
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3332 Debugger listening on ws://127.0.0.1:44626/295fddea-d2dd-418e-bbb5-332607330668
For help, see: https://nodejs.org/en/docs/inspector

/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3500 Extension host terminated unexpectedly. Code:  null  Signal:  SIGABRT
t._onExtensionHostCrashed @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3500
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2542 Extension host terminated unexpectedly.
t.onDidNotificationChange @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2542
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3332 Extension Host
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3332 dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/gonzo/.vscode-insiders/extensions/ritwickdey.liveserver-5.3.1/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/gonzo/.vscode-insiders/extensions/ritwickdey.liveserver-5.3.1/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3334 [Extension Host] debugger listening on port 53174
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3332 Extension Host
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3332 Debugger listening on ws://127.0.0.1:53174/9f66a20a-5dc2-4823-8db6-c308a49e547b
For help, see: https://nodejs.org/en/docs/inspector

/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3500 Extension host terminated unexpectedly. Code:  null  Signal:  SIGABRT
t._onExtensionHostCrashed @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3500
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2542 Extension host terminated unexpectedly.
t.onDidNotificationChange @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2542
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3332 Extension Host
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3332 dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/gonzo/.vscode-insiders/extensions/ritwickdey.liveserver-5.3.1/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/gonzo/.vscode-insiders/extensions/ritwickdey.liveserver-5.3.1/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

Extension version: 5.3.1
VS Code version: Code - Insiders 1.31.0-insider (9fe48f15b1a252a0e9e1ef5975301203baf10b8a, 2019-01-25T08:11:48.342Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (0.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by rjoydip** [comment]
This issue is not coming from the live server. `dyld: Symbol not found:` coming when the binary build of `fsevents`. It happens due to node version mismatch.

**Comment by tedonmain** [comment]
OK thanks. What version of Node will work? I'm at ~ $ node --version
v11.6.0

**Comment by milesros** [comment]
Facing this the same issue, what is the fix for this?

**Comment by tedonmain** [comment]
Right now I’m removing it from the extensions cause it’s crashing the extension server. Btw it showed up in vscode today after update. Right now I’m doing npx live-server in the root and it’s reporting some errors but then it starts and does live update. Not ideal but it keeps me working.

**Comment by milesros** [comment]
Same, i literally updated vscode to version 1.31 and got the error... impossible to debug as well. I download the previous stable version 1.30 (where there is no issue...for now). 

I really hope they find a fix for this.

**Comment by tedonmain** [comment]
It is working on Ubuntu 18.04 node 8.10 today so maybe node 8.x is it. I’m running node 10.x on MacOs where the problem is.

**Comment by milesros** [comment]
hmm, odd. Like i said, i can't even tell what/where the root of the issue lies.

**Comment by tedonmain** [comment]
The guy who maintains it is unable to devote enough time to it and is looking for someone to take it over.

**Comment by ritwickdey** [comment]
Please upgrade LiveServer to 5.4.0 (just now published) and let me know

**Comment by tedonmain** [comment]
Back in business! Thanks! It works in both Insider and Code. This is one sweet little number, so many thoughtful features, so dang useful. Thanks for creating it.

**Comment by SethuSenthil** [comment]
I'm having this issue on the stable version too which I updated today. Whats the solution?

**Comment by Gaben01** [comment]
I think I'm facing the same problem and I have the latest versione installed :
 INFO no standard startup: not the explorer viewlet

**Comment by tedonmain** [comment]
Try launching live server directly in your project root: 

npx live-server 

This will ensure live-server can start/reload on save.

**Comment by ritwickdey** [comment]
Hi, there is a versioning issue that we're again facing in v5.5.0 

You can install v5.4.0 from vscode marketplace to resolve the issue temporarily  https://github.com/ritwickdey/vscode-live-server/issues/285
